### PR TITLE
add playbackRate control event

### PR DESCRIPTION
**Pull request by newming**

### CODE REVIEW

**Comment by DIYgod** [comment]
What is the point? This event has already been bound on [setting.js#L70](https://github.com/MoePlayer/DPlayer/blob/master/src/setting.js#L70)

**Comment by newming** [comment]
I find it doesn’t take effect, so ...

**Comment by DIYgod** [comment]
It has been fixed in https://github.com/MoePlayer/DPlayer/commit/7a2a40e8a9192d5749380c79ba1a19dba1e91a4f, but I haven't released new version yet.

**Comment by newming** [comment]
when you want to release next version ?:smile:

**Comment by kn007** [comment]
@newming 看心情，现在模块整合还没完呢。。。
急用可以自己编译。

**Comment by newming** [comment]
好的，非常感谢。给你们添麻烦了。。。第一次 PR。

**Pull request closed without merging**
